# @format

AWSTemplateFormatVersion: '2010-09-09'

Description: Database MyFinances AWS Cloudformation

Parameters:
  StackName:
    Type: String
    Description: Name of the stack

Resources:
  StocksPriceDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Description: Stocks price DynamoDB Table
    Properties:
      TableName: !Sub ${StackName}-stocks-price
      AttributeDefinitions:
        - AttributeName: hashKey
          AttributeType: S
        - AttributeName: rangeKey
          AttributeType: S
      KeySchema:
        - AttributeName: hashKey
          KeyType: HASH
        - AttributeName: rangeKey
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  StocksPriceDynamoDBTableRef:
    Value: !Ref StocksPriceDynamoDBTable
