# @format

AWSTemplateFormatVersion: '2010-09-09'

Description: Database AWS Cloudformation

Parameters:
  StackName:
    Type: String

Resources:
  StocksPriceDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Description: Stocks price DynamoDB Table
    Properties:
      TableName: !Sub ${StackName}-stocks-price
      AttributeDefinitions:
        - AttributeName: hashKey
          AttributeType: S
        - AttributeName: rangeKey
          AttributeType: S
      KeySchema:
        - AttributeName: hashKey
          KeyType: HASH
        - AttributeName: rangeKey
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  UsersDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Description: User Data DynamoDB Table
    Properties:
      AttributeDefinitions:
        - AttributeName: hashKey
          AttributeType: S
        - AttributeName: searchHelper
          AttributeType: S
      KeySchema:
        - AttributeName: hashKey
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: index-search-helper
          KeySchema:
            - AttributeName: searchHelper
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY

  InvestmentsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Description: Investments DynamoDB Table
    Properties:
      TableName: !Sub ${StackName}-investments
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: hashKey
          AttributeType: S
        - AttributeName: rangeKey
          AttributeType: S
      KeySchema:
        - AttributeName: hashKey
          KeyType: HASH
        - AttributeName: rangeKey
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: range-key-index
          KeySchema:
            - AttributeName: rangeKey
              KeyType: HASH
            - AttributeName: hashKey
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  StocksPriceDynamoDBTableRef:
    Value: !Ref StocksPriceDynamoDBTable
  StocksPriceDynamoDBTableArn:
    Value: !GetAtt StocksPriceDynamoDBTable.Arn
  UsersDynamoDBTableRef:
    Value: !Ref UsersDynamoDBTable
  UsersDynamoDBTableArn:
    Value: !GetAtt UsersDynamoDBTable.Arn
  InvestmentsDynamoDBTableRef:
    Value: !Ref InvestmentsDynamoDBTable
  InvestmentsDynamoDBTableArn:
    Value: !GetAtt InvestmentsDynamoDBTable.Arn
