# @format

AWSTemplateFormatVersion: '2010-09-09'

Description: My Finances AWS Cloudformation

Parameters:
  StackName:
    Type: String
    Default: my-finances
    AllowedValues:
      - my-finances

Resources:
  DatabaseCloudformationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/my-finances-cloudformation/database.yml
      Parameters:
        StackName: !Sub ${StackName}

  StocksPriceCronjobCloudformationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/my-finances-cloudformation/stocks-price-cronjob.yml
      Parameters:
        StackName: !Sub ${StackName}

Outputs:
  Region:
    Description: Region
    Value: !Sub ${AWS::Region}
  StackName:
    Description: StackName
    Value: !Sub ${StackName}
  Test:
    Value: !GetAtt DatabaseCloudformationStack.Outputs.StocksPriceDynamoDBTableRef
