# @format

AWSTemplateFormatVersion: '2010-09-09'

Description: My Finances AWS Cloudformation

Parameters:
  StackName:
    Type: String
    Default: my-finances
    AllowedValues:
      - my-finances

Resources:
  DatabaseCloudformationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/my-finances-cloudformation/database.yml
      Parameters:
        StackName: !Sub ${StackName}

  CognitoCloudformationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/my-finances-cloudformation/cognito.yml
      Parameters:
        StackName: !Sub ${StackName}

  AppSyncApiCloudFormationStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - CognitoCloudformationStack
      - DatabaseCloudformationStack
    Properties:
      TemplateURL: https://s3.amazonaws.com/my-finances-cloudformation/appsync.yml
      Parameters:
        StackName: !Sub ${StackName}
        UserPoolId: !GetAtt CognitoCloudformationStack.Outputs.CognitoUserPoolId
        StocksPriceDynamoDBTableRef: !GetAtt DatabaseCloudformationStack.Outputs.StocksPriceDynamoDBTableRef
        StocksPriceDynamoDBTableArn: !GetAtt DatabaseCloudformationStack.Outputs.StocksPriceDynamoDBTableArn
        UsersDynamoDBTableRef: !GetAtt DatabaseCloudformationStack.Outputs.UsersDynamoDBTableRef
        UsersDynamoDBTableArn: !GetAtt DatabaseCloudformationStack.Outputs.UsersDynamoDBTableArn
        InvestmentsDynamoDBTableRef: !GetAtt DatabaseCloudformationStack.Outputs.InvestmentsDynamoDBTableRef
        InvestmentsDynamoDBTableArn: !GetAtt DatabaseCloudformationStack.Outputs.InvestmentsDynamoDBTableArn
        IdentityPoolAuthorizedIAMRoleRef: !GetAtt CognitoCloudformationStack.Outputs.IdentityPoolAuthorizedIAMRoleRef

  StocksPriceCronjobCloudformationStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DatabaseCloudformationStack
    Properties:
      TemplateURL: https://s3.amazonaws.com/my-finances-cloudformation/stocks-price-cronjob.yml
      Parameters:
        StackName: !Sub ${StackName}
        StocksPriceDynamoDBTableArn: !GetAtt DatabaseCloudformationStack.Outputs.StocksPriceDynamoDBTableArn
        IdentityPoolUnauthorizedIAMRoleRef: !GetAtt CognitoCloudformationStack.Outputs.IdentityPoolUnauthorizedIAMRoleRef

Outputs:
  Region:
    Description: Region
    Value: !Sub ${AWS::Region}
  StackName:
    Description: StackName
    Value: !Sub ${StackName}
  CognitoUserPoolClientId:
    Description: Cognito UserPool ClientId
    Value: !GetAtt CognitoCloudformationStack.Outputs.CognitoUserPoolClientId
  CognitoUserPoolId:
    Description: Cognito UserPool Id
    Value: !GetAtt CognitoCloudformationStack.Outputs.CognitoUserPoolId
  CognitoIdentityPool:
    Description: Cognito IdentityId
    Value: !GetAtt CognitoCloudformationStack.Outputs.CognitoIdentityPool
  AppSyncGraphQLApiEndpoint:
    Description: AppSync GraphQL API Endpoint
    Value: !GetAtt AppSyncApiCloudFormationStack.Outputs.AppSyncGraphQLApiEndpoint
